apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  labels:
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    app.kubernetes.io/name: '{{ include "chart.name" . }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/part-of: '{{ .Chart.Name }}'
data:
  host: '{{ .Values.database.host }}'
  password: '{{ .Values.database.credentials.password }}'
  username: '{{ .Values.database.credentials.username }}'
type: Opaque
