import type { Chart } from 'cdk8s';

import type { TimonelLogger } from './utils/logger.js';

/**
 * Configuration used by the legacy `UmbrellaChartTemplate` compatibility API.
 *
 * New library code should normally build subcharts with `Rutter` and compose them with
 * `UmbrellaRutter`. This interface remains public for the template/CLI compatibility layer.
 */
export interface ChartProps {
  /** Helm chart name. */
  name: string;
  /** Helm chart semantic version. */
  version: string;
  /** Human-readable chart description. */
  description: string;
  /** Optional default Kubernetes namespace. */
  namespace?: string;
  /** Labels applied by compatibility template helpers. */
  labels?: Record<string, string>;
  /** Annotations applied by compatibility template helpers. */
  annotations?: Record<string, string>;
  /** Optional service descriptors generated by the umbrella compatibility template. */
  services?: Array<{
    name: string;
    port: number;
    targetPort: number;
  }>;
  /** Optional subchart descriptors consumed by the umbrella compatibility template. */
  subcharts?: Array<{
    name: string;
    chart: Chart | ((scope: Chart, id: string) => Chart) | unknown;
    version?: string;
    enabled?: boolean;
    /** Additional template-specific properties. */
    [key: string]: unknown;
  }>;
  /** Additional template-specific properties retained for compatibility. */
  [key: string]: unknown;
  /**
   * Custom logger instance.
   * @since 2.13.0
   */
  logger?: TimonelLogger;
}

/**
 * Serializable subchart entry stored by the CLI in `umbrella.config.json`.
 */
export interface SubchartProps {
  /** Subchart name. */
  name: string;
  /** Subchart version recorded in the CLI configuration. */
  version: string;
  /** Project-relative path to the subchart TypeScript entry point. */
  path: string;
}
