/**
 * @fileoverview UmbrellaRutter class for managing Helm umbrella charts with multiple subcharts
 * @since 2.8.0+
 */
import {
  copyFileSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'fs';
import { basename, dirname, join, sep } from 'path';

import type { HelmChartMeta } from './helmChartWriter.js';
import type { Rutter } from './rutter.js';
import { createLogger, type TimonelLogger } from './utils/logger.js';
import { SecurityUtils } from './security.js';
import { dumpHelmAwareYaml } from './utils/helmYamlSerializer.js';

/** Common Helm dependency metadata shared by every umbrella subchart entry. */
interface SubchartBaseSpec {
  /** Name of the Helm dependency. */
  name: string;
  /** Helm condition for enabling/disabling the dependency. */
  condition?: string;
  /** Tags for grouping dependencies. */
  tags?: string[];
  /** Repository URL written to the parent Chart.yaml dependency. */
  repository?: string;
}

/** A subchart generated by a Timonel Rutter instance. */
export interface GeneratedSubchartSpec extends SubchartBaseSpec {
  /** Rutter instance that generates the subchart. */
  rutter: Rutter;
  /** Dependency version; defaults to `0.1.0` for compatibility. */
  version?: string;
  /** Generated subcharts cannot also be copied from a source directory. */
  sourceDirectory?: never;
}

/** A remote dependency referenced in Chart.yaml without local synthesis. */
export interface RemoteSubchartSpec extends SubchartBaseSpec {
  /** No Rutter instance is used for dependency-only entries. */
  rutter?: never;
  /** Exact/range dependency version required by Helm. */
  version: string;
  /** Remote repository URL required for dependency-only remote entries. */
  repository: string;
  /** Remote dependencies are not copied into `charts/`. */
  sourceDirectory?: never;
}

/** An already-existing local chart copied into the umbrella `charts/` directory. */
export interface VendoredSubchartSpec extends SubchartBaseSpec {
  /** No Rutter instance is used for vendored entries. */
  rutter?: never;
  /** Dependency version declared in the parent Chart.yaml. */
  version: string;
  /** Existing chart directory to copy without synthesizing it. */
  sourceDirectory: string;
}

/**
 * Configuration for a generated, remote, or vendored umbrella dependency.
 *
 * @since 2.8.0+
 */
export type SubchartSpec = GeneratedSubchartSpec | RemoteSubchartSpec | VendoredSubchartSpec;

/**
 * Configuration properties for UmbrellaRutter
 *
 * @since 2.8.0+
 */
export interface UmbrellaRutterProps {
  /** Metadata for the umbrella chart */
  meta: HelmChartMeta;
  /** Array of subchart specifications */
  subcharts: SubchartSpec[];
  /** Default values for the umbrella chart */
  defaultValues?: Record<string, unknown>;
  /**
   * Custom logger instance
   * @since 2.13.0
   */
  logger?: TimonelLogger;
  /** Environment-specific values */
  envValues?: Record<string, Record<string, unknown>>;
}

/**
 * UmbrellaRutter manages multiple Rutter instances as subcharts
 * to create Helm umbrella charts with dependencies.
 *
 * @example
 * ```typescript
 * const umbrella = new UmbrellaRutter({
 *   meta: { name: 'my-app', version: '1.0.0' },
 *   subcharts: [
 *     { name: 'frontend', rutter: frontendChart },
 *     { name: 'backend', rutter: backendChart }
 *   ]
 * });
 *
 * umbrella.write('./my-app');
 * ```
 *
 * @since 2.8.0+
 */
export class UmbrellaRutter {
  private readonly props: UmbrellaRutterProps;
  private readonly logger: TimonelLogger;

  /**
   * Creates a new UmbrellaRutter instance
   *
   * @param props - Configuration properties for the umbrella chart
   * @throws {Error} If chart metadata is invalid
   *
   * @since 2.8.0+
   */
  constructor(props: UmbrellaRutterProps) {
    this.logger = props.logger ?? createLogger('umbrella-rutter');
    this.logger.info('Initializing umbrella chart', {
      name: props.meta.name,
      version: props.meta.version,
      subchartsCount: props.subcharts.length,
    });

    // Validate chart metadata
    this.validateMetadata(props.meta);
    this.props = props;
  }

  private validateMetadata(meta: HelmChartMeta): void {
    // Validate chart name follows Helm conventions
    // eslint-disable-next-line security/detect-unsafe-regex -- Safe regex for chart name validation
    if (!/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/.test(meta.name)) {
      throw new Error('Chart name must contain only lowercase letters, numbers, and dashes');
    }

    // Validate semantic versioning
    // eslint-disable-next-line security/detect-unsafe-regex -- Safe regex for semver validation
    if (!/^\d+\.\d+\.\d+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$/.test(meta.version)) {
      throw new Error('Chart version must follow semantic versioning (e.g., 1.0.0)');
    }
  }

  /** Validate a subchart entry before filesystem or Chart.yaml operations. */
  private validateSubchart(subchart: SubchartSpec): void {
    if (!SecurityUtils.isValidSubchartName(subchart.name)) {
      throw new Error(`Invalid subchart name: ${SecurityUtils.sanitizeLogMessage(subchart.name)}`);
    }

    const hasRutter = 'rutter' in subchart && Boolean(subchart.rutter);
    const hasSourceDirectory =
      'sourceDirectory' in subchart && typeof subchart.sourceDirectory === 'string';

    if (!hasRutter && !subchart.version) {
      throw new Error(`Dependency-only subchart '${subchart.name}' requires a version`);
    }

    if (!hasRutter && !hasSourceDirectory && !subchart.repository) {
      throw new Error(`Remote subchart '${subchart.name}' requires a repository`);
    }

    if (hasRutter && hasSourceDirectory) {
      throw new Error(`Subchart '${subchart.name}' cannot use both rutter and sourceDirectory`);
    }
  }

  /** Copy a vendored chart recursively without following symbolic links. */
  private copyVendoredChart(sourceDirectory: string, destinationDirectory: string): void {
    const source = SecurityUtils.validatePath(sourceDirectory, process.cwd(), {
      allowAbsolute: true,
    });

    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Source path validated above.
    if (!existsSync(source) || !lstatSync(source).isDirectory()) {
      throw new Error(
        `Vendored subchart source must be an existing directory: ${SecurityUtils.sanitizeLogMessage(sourceDirectory)}`,
      );
    }

    // Canonicalize existing path components before containment checks so symlinked
    // parent aliases cannot hide a physical source/destination overlap.
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Source was validated and must exist above.
    const canonicalSource = realpathSync(source);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Destination parent is created and validated by write().
    const canonicalDestinationParent = realpathSync(dirname(destinationDirectory));
    const canonicalDestination = join(canonicalDestinationParent, basename(destinationDirectory));
    const sourceContainsDestination =
      canonicalDestination === canonicalSource ||
      canonicalDestination.startsWith(`${canonicalSource}${sep}`);
    const destinationContainsSource = canonicalSource.startsWith(`${canonicalDestination}${sep}`);
    if (sourceContainsDestination || destinationContainsSource) {
      throw new Error('Vendored subchart source and destination must not overlap');
    }

    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Destination path validated by chartsDir containment.
    if (existsSync(destinationDirectory)) {
      throw new Error(`Vendored subchart destination already exists: ${destinationDirectory}`);
    }

    try {
      this.copyDirectoryTree(source, destinationDirectory);
    } catch (error) {
      rmSync(destinationDirectory, { recursive: true, force: true });
      throw error;
    }
  }

  /** Copy one directory tree deterministically while rejecting symlink escapes. */
  private copyDirectoryTree(sourceDirectory: string, destinationDirectory: string): void {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Paths validated by caller/base recursion.
    mkdirSync(destinationDirectory, { recursive: true });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- Source path validated by caller/base recursion.
    const entries = readdirSync(sourceDirectory, { withFileTypes: true }).sort((a, b) =>
      a.name.localeCompare(b.name),
    );

    for (const entry of entries) {
      const sourcePath = SecurityUtils.validatePath(
        join(sourceDirectory, entry.name),
        sourceDirectory,
      );
      const destinationPath = SecurityUtils.validatePath(
        join(destinationDirectory, entry.name),
        destinationDirectory,
      );

      // eslint-disable-next-line security/detect-non-literal-fs-filename -- Source path validated above.
      const stats = lstatSync(sourcePath);
      if (stats.isSymbolicLink()) {
        throw new Error(`Vendored subchart cannot contain symbolic links: ${entry.name}`);
      }
      if (stats.isDirectory()) {
        this.copyDirectoryTree(sourcePath, destinationPath);
        continue;
      }
      if (!stats.isFile()) {
        throw new Error(`Vendored subchart contains unsupported filesystem entry: ${entry.name}`);
      }

      copyFileSync(sourcePath, destinationPath);
    }
  }

  /**
   * Write the umbrella chart with all subcharts to the output directory
   *
   * Creates the complete umbrella chart structure including:
   * - Parent Chart.yaml with dependencies
   * - Parent values.yaml with global and subchart values
   * - Individual subchart directories under charts/
   * - NOTES.txt template
   *
   * @param outDir - Output directory path for the umbrella chart
   * @returns Promise that resolves when the chart is written
   * @throws {Error} If output directory path is invalid
   *
   * @example
   * ```typescript
   * await umbrella.write('./dist/my-umbrella-chart');
   * ```
   *
   * @since 2.8.0+
   */
  async write(outDir: string): Promise<void> {
    // Validate output directory path
    const validatedOutDir = SecurityUtils.validatePath(outDir, process.cwd(), {
      allowAbsolute: true,
    });

    // Create output directory structure
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    mkdirSync(validatedOutDir, { recursive: true });
    const chartsDir = SecurityUtils.validatePath(join(validatedOutDir, 'charts'), process.cwd(), {
      allowAbsolute: true,
    });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    mkdirSync(chartsDir, { recursive: true });

    // Materialize only locally-owned dependencies under charts/. Remote dependencies remain
    // Chart.yaml entries and are resolved by Helm dependency tooling.
    for (const subchart of this.props.subcharts) {
      this.validateSubchart(subchart);

      if ('rutter' in subchart && subchart.rutter) {
        const subchartDir = SecurityUtils.validatePath(join(chartsDir, subchart.name), chartsDir);
        await subchart.rutter.write(subchartDir);
        continue;
      }

      if ('sourceDirectory' in subchart && subchart.sourceDirectory) {
        const subchartDir = SecurityUtils.validatePath(join(chartsDir, subchart.name), chartsDir);
        this.copyVendoredChart(subchart.sourceDirectory, subchartDir);
      }
    }

    // Generate parent Chart.yaml with dependencies
    this.writeParentChart(validatedOutDir);

    // Generate parent values.yaml
    this.writeParentValues(validatedOutDir);

    // Generate empty templates directory (umbrella charts typically don't have templates)
    const templatesDir = SecurityUtils.validatePath(
      join(validatedOutDir, 'templates'),
      process.cwd(),
      { allowAbsolute: true },
    );
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    mkdirSync(templatesDir, { recursive: true });
    const notesPath = SecurityUtils.validatePath(
      join(validatedOutDir, 'templates', 'NOTES.txt'),
      process.cwd(),
      { allowAbsolute: true },
    );
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    writeFileSync(notesPath, this.generateNotesTemplate());
  }

  private writeParentChart(outDir: string): void {
    const chartYaml = {
      apiVersion: 'v2',
      name: this.props.meta.name,
      description: this.props.meta.description || `${this.props.meta.name} umbrella chart`,
      type: 'application',
      version: this.props.meta.version,
      appVersion: this.props.meta.appVersion,
      keywords: this.props.meta.keywords || [],
      home: this.props.meta.home,
      sources: this.props.meta.sources,
      maintainers: this.props.meta.maintainers,
      dependencies: this.props.subcharts.map((subchart) => {
        // Subchart name already validated in write() method
        return {
          name: subchart.name,
          version: subchart.version || '0.1.0',
          repository: subchart.repository || `file://./charts/${subchart.name}`,
          ...(subchart.condition && { condition: subchart.condition }),
          ...(subchart.tags && { tags: subchart.tags }),
        };
      }),
    };

    const chartYamlPath = SecurityUtils.validatePath(join(outDir, 'Chart.yaml'), process.cwd(), {
      allowAbsolute: true,
    });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    writeFileSync(chartYamlPath, dumpHelmAwareYaml(chartYaml));
  }

  private writeParentValues(outDir: string): void {
    const values: Record<string, unknown> = {
      // Global values that can be shared across subcharts
      global: {},
      // Individual subchart values
      ...this.props.defaultValues,
    };

    // Add subchart-specific value sections
    for (const subchart of this.props.subcharts) {
      if (!(subchart.name in values)) {
        values[subchart.name] = {
          enabled: true,
        };
      }
    }

    const valuesYamlPath = SecurityUtils.validatePath(join(outDir, 'values.yaml'), process.cwd(), {
      allowAbsolute: true,
    });
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
    writeFileSync(valuesYamlPath, dumpHelmAwareYaml(values));

    // Write environment-specific values files
    if (this.props.envValues) {
      for (const [env, envVals] of Object.entries(this.props.envValues)) {
        // Use centralized environment name sanitization
        const sanitizedEnv = SecurityUtils.sanitizeEnvironmentName(env);
        const envValues = this.deepMerge(values, envVals);
        const envValuesPath = SecurityUtils.validatePath(
          join(outDir, `values-${sanitizedEnv}.yaml`),
          process.cwd(),
          { allowAbsolute: true },
        );
        // eslint-disable-next-line security/detect-non-literal-fs-filename -- validated path
        writeFileSync(envValuesPath, dumpHelmAwareYaml(envValues));
      }
    }
  }

  private deepMerge(
    target: Record<string, unknown>,
    source: Record<string, unknown>,
  ): Record<string, unknown> {
    const result = { ...target };
    for (const [key, value] of Object.entries(source)) {
      if (value && typeof value === 'object' && !Array.isArray(value)) {
        // eslint-disable-next-line security/detect-object-injection -- Safe object property access in deep merge
        result[key] = this.deepMerge(
          // eslint-disable-next-line security/detect-object-injection -- Safe object property access in deep merge
          (result[key] as Record<string, unknown>) || {},
          value as Record<string, unknown>,
        );
      } else {
        // eslint-disable-next-line security/detect-object-injection -- Safe object property access in deep merge
        result[key] = value;
      }
    }
    return result;
  }

  private generateNotesTemplate(): string {
    return `1. Get the application URLs by running these commands:
{{- range $subchart := .Values }}
{{- if and (hasKey $subchart "enabled") $subchart.enabled }}
  {{ $subchart | quote }} is enabled
{{- end }}
{{- end }}

2. Check the status of subcharts:
  helm list -A

3. For more information about each dependency, check:
${this.props.subcharts
  .map((subchart) => {
    const isLocal =
      ('rutter' in subchart && Boolean(subchart.rutter)) ||
      ('sourceDirectory' in subchart && Boolean(subchart.sourceDirectory));
    return isLocal
      ? `  - charts/${subchart.name}/README.md`
      : `  - ${subchart.name}: ${subchart.repository}`;
  })
  .join('\n')}
`;
  }
}
