name: Automated Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  check-status:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check CI Status
        uses: actions/github-script@v7
        with:
          script: |
            const branchRef = '${{ inputs.branch }}'.replace(/[^a-zA-Z0-9\/_.-]/g, '');
            console.log(`Checking status for branch: ${branchRef}`);

            const { data: checks } = await github.rest.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: branchRef
            });

            console.log(`Found ${checks.check_runs.length} check runs`);

            const requiredChecks = [
              // Node.js v20 build and test pipeline
              'build (20)',
              // Node.js v22 build and test pipeline
              'build (22)',
              // Security audit and vulnerability scanning
              'security'
            ];
            const failedChecks = [];

            for (const checkName of requiredChecks) {
              const check = checks.check_runs.find(c => c.name === checkName);
              if (!check) {
                console.log(`❌ Missing check: ${checkName}`);
                failedChecks.push(checkName);
              } else if (check.conclusion !== 'success') {
                console.log(`❌ Failed check: ${checkName} (${check.conclusion})`);
                failedChecks.push(checkName);
              } else {
                console.log(`✅ Passed check: ${checkName}`);
              }
            }

            if (failedChecks.length > 0) {
              core.setFailed(`Required checks failed: ${failedChecks.join(', ')}`);
            } else {
              console.log('✅ All required checks passed - proceeding with release');
            }

  release:
    runs-on: ubuntu-latest
    environment: npm-prd
    needs: check-status
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Build and test
        run: |
          pnpm run build
          pnpm run lint
          pnpm run test

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
